import { TokenInfo } from './token';

export const knownTokens: TokenInfo[] = [
  { mintAddress: "So11111111111111111111111111111111111111112", symbol: "WSOL", decimals: 9, logoURI: "/token logos/Wsol.webp", name: "Wrapped SOL" },
  { mintAddress: "Gh9ZwEmdLJ8DscKNTkTqPbNwLNNBjuSzaG9Vp2KGtKJr", symbol: "USDC Dev", decimals: 6, logoURI: "/token logos/Usdc.webp", name: "USD Coin Dev" },
  { mintAddress: "mnt3Mc5iK8UNZheyPmS9UQKrM6Rz5s4d8x63BUv22F9", symbol: "DEXV3-USDT", decimals: 6, logoURI: "/token logos/Usdt.webp", name: "Dex V3 Tether USD" },
  { mintAddress: "mntCAkd76nKSVTYxwu8qwQnhPcEE9JyEbgW6eEpwr1N", symbol: "DEXV3-SAROS", decimals: 6, logoURI: "/token logos/Saros.webp", name: "Dex V3 Saros" },
  { mintAddress: "mntC2RhmYyooDcX6HeTpLmd4v673ak9Cn7J31FG41d6", symbol: "DEXV3-ME", decimals: 6, logoURI: "/token logos/Me.webp", name: "Dex V3 ME Token" },
  { mintAddress: "mnt72NV74VfWGbSJqYswLbgPds22hVvspjqBzi7dc4j", symbol: "DEXV3-JUP", decimals: 6, logoURI: "/token logos/Jupiter.webp", name: "Dex V3 Jupiter" },
  { mintAddress: "mntLe6A4SELrDDiSsdp1wNe64EZ5TsM9gtyFzGPouTr", symbol: "Coin98-USDC", decimals: 6, logoURI: "/token logos/Coin-98.webp", name: "Coin98 USD Coin" },
  { mintAddress: "mntpxwsakkExmJb82nkJDGsVZyNapvoe1q7awjK37F4", symbol: "DEXV3-VIRTUAL", decimals: 9, logoURI: "/token logos/Virtual.webp", name: "Dex V3 Virtual" },
  { mintAddress: "mntRT93wUdszL1e9QoLGtWoEfAYzFgofePyT8fTTe7z", symbol: "DEXV3-C98", decimals: 6, logoURI: "", name: "Dex V3 Coin98" },
  { mintAddress: "3SzKbuzdifpU215T5dt34VnHeUaFPD9hSrK7d1Q78VAM", symbol: "DEXV3-TFT", decimals: 9, logoURI: "/token logos/TFT.webp", name: "Dex V3 TFT" },
  { mintAddress: "9mBbBsEuffHHh88gBt8oqY14NmFWF55veCP9XXbgaaa4", symbol: "SANGROS", decimals: 9, logoURI: "", name: "Sangros Token" },
  { mintAddress: "2nAvUxWh4DSiNJhfovh3Mv1XXKwBwqqH3m2Cit9NeSWH", symbol: "SPL Token", decimals: 9, logoURI: "", name: "Unknown SPL Token" },
  { mintAddress: "9oNgMizmQrEqsNJB1XEwLA81a3xik7e4va7kfNpNnfzW", symbol: "SPL Token", decimals: 6, logoURI: "", name: "Unknown SPL Token" },
  { mintAddress: "5xpw2uucPLH5RKFfVRxon2xKMdS7kDMprxkoimUKeE99", symbol: "C98DOG", decimals: 9, logoURI: "/token logos/Dogwifhat.webp", name: "Coin98 Dog" },
  { mintAddress: "CXk2AMBfi3TwaEL2468s6zP8xq9NxTXjp9gjMgzeUynM", symbol: "PAYPAL USD", decimals: 6, logoURI: "/token logos/Paypal.webp", name: "PYUSD" },
  { mintAddress: "43zS2spaz1Doi1KDevSFKxf1KWhNDfjwbnXL5j7GDNJ8", symbol: "SPL Token", decimals: 9, logoURI: "", name: "Unknown SPL Token" },
  { mintAddress: "AgMPMPdUiDQ2CNUVKniK8snHnBK5kgdS9FVDc3etSX3o", symbol: "SPL Token", decimals: 9, logoURI: "", name: "Unknown SPL Token" },
  { mintAddress: "4jE3owHyXkj7399ncfVSPbtg9XetXNwWhRTxUjAd7vWB", symbol: "dogwifhat", decimals: 9, logoURI: "/token logos/Dogwifhat.webp", name: "Dogwifhat" },
  { mintAddress: "91uNnxoN8cFmtWr5942kRu5aTJttzTqDBrrwQkmMrsuG", symbol: "NENE", decimals: 6, logoURI: "/token logos/Nene.webp", name: "Nene Token" },
  { mintAddress: "5wBLaYUPxw9iuZNa5K6yn1zLVYauESXSJze1yu7XCmz2", symbol: "TEST", decimals: 9, logoURI: "/token logos/TEST.webp", name: "Test Token" },
  { mintAddress: "FWHKuHvnFnfXZo1EG246egPAcLE4uXCVKmSm7Xc7gdsK", symbol: "HORJET", decimals: 9, logoURI: "", name: "Horjet Coin" },
  { mintAddress: "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU", symbol: "USDC", decimals: 6, logoURI: "/token logos/Usdc.webp", name: "USD Coin" },
  { mintAddress: "GRw1812tVGx1u6n9BhuMraxCj35P6YqycqJSxH1g6cxd", symbol: "SPL Token", decimals: 9, logoURI: "", name: "Unknown SPL Token" },
  { mintAddress: "FAg5dMk72hEBkohyirpvVmiTQmoRNwZsKhYF4ar8EcUL", symbol: "SPL Token", decimals: 9, logoURI: "", name: "Unknown SPL Token" },
  { mintAddress: "2wSKgsYegAKcyLKCBS7cediwfyQmfjPVZBTs9D7furgS", symbol: "SPL Token", decimals: 5, logoURI: "", name: "Unknown SPL Token" },
  { mintAddress: "5hXPJ168xDTs36hN4egujTdmZMpbKP5ConZdGLtzujVs", symbol: "SPL Token", decimals: 5, logoURI: "", name: "Unknown SPL Token" },
  { mintAddress: "4Gs9NLW8CTnk39NkMAJdvFnAEmC8ZStkXhfajKgx6Vwp", symbol: "SPL Token", decimals: 6, logoURI: "", name: "Unknown SPL Token" },
  { mintAddress: "3GmtLYzTtdCGt5uCkoMkBNVhLuienZd5rtCw77bDDgks", symbol: "SPL Token", decimals: 6, logoURI: "", name: "Unknown SPL Token" },
  { mintAddress: "823dshUxb3RNf1NXVX28smC7VGHaTusESJJX3GpKW2R9", symbol: "SPL Token", decimals: 2, logoURI: "", name: "Unknown SPL Token" },
  { mintAddress: "5QhsyriyneDvoZCt9Cji5GyrXRZ1pfBoj372PQbZ3eVz", symbol: "SPL Token", decimals: 4, logoURI: "", name: "Unknown SPL Token" },
  { mintAddress: "6GuHXVypQd7JxNm9xcic1PJupWUDwH5Pig1SHGDQo56t", symbol: "SPL Token", decimals: 8, logoURI: "", name: "Unknown SPL Token" },
  { mintAddress: "DyyL98witZXFskq48d47TkDDUT2k2SCLKjDuqjSyh6yC", symbol: "OPOS", decimals: 9, logoURI: "/token logos/OPOS.webp", name: "Opos Coin" },
  { mintAddress: "9WNGiZEescNbYYRh8iFNLwXerk6Cxvs4Lo5tckQDpJDt", symbol: "OPOS", decimals: 9, logoURI: "/token logos/OPOS.webp", name: "Opos Coin" },
];
